import type { AvatarId } from './domain.js';
export interface JoinResponse { participantId: string; livekitUrl: string; token: string; role?: 'host' | 'participant'; hostToken?: string }
export interface CreateRoomResponse { roomId: string; hostUrl: string; participantUrl: string; hostToken?: string; participantToken?: string; maxParticipants?: number }
type Fetcher = typeof fetch;
const request = async <T>(path: string, init: RequestInit, fetcher: Fetcher): Promise<T> => { const response = await fetcher(path, init); const payload = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(payload.error ?? 'network_error'); return payload; };
export function createRoom(fetcher: Fetcher): Promise<string>;
export function createRoom(maxParticipants?: number, fetcher?: Fetcher): Promise<CreateRoomResponse>;
export async function createRoom(maxParticipantsOrFetcher: number | Fetcher = 10, fetcher: Fetcher = fetch): Promise<CreateRoomResponse | string> { const legacy = typeof maxParticipantsOrFetcher === 'function'; const maxParticipants = legacy ? 10 : maxParticipantsOrFetcher; const requestFetcher = legacy ? maxParticipantsOrFetcher : fetcher; const init: RequestInit = legacy ? { method: 'POST' } : { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ maxParticipants }) }; const response = await request<CreateRoomResponse>('/api/rooms', init, requestFetcher); return legacy ? response.roomId : response; }
export const joinRoom = (roomId: string, identity: { nickname: string; avatarId: AvatarId; hostToken?: string; participantToken?: string }, fetcher: Fetcher = fetch): Promise<JoinResponse> => request(`/api/rooms/${encodeURIComponent(roomId)}/join`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(identity) }, fetcher);
